DROP DATABASE IF exists dath;
CREATE DATABASE dath;
USE dath;
CREATE TABLE PG_CATEGORIES(
	 CATEGORY_ID INT auto_increment primary KEY,
	 CATEGORY_NAME varchar(100) NOT NULL,
	 DESCRIPTION VARCHAR(300),
	 SORT_INDEX INT NOT NULL,
	 CATEGORY_STATUS INT NOT NULL DEFAULT 1
);

INSERT INTO PG_CATEGORIES(CATEGORY_NAME, DESCRIPTION, SORT_INDEX) VALUES ('Quần short','',1);

	
CREATE TABLE PG_ROLES(
	ROLE_ID INT auto_increment primary KEY,
	ROLE_NAME VARCHAR(100) NOT NULL,
	PARENT INT
);
	INSERT INTO PG_ROLES(ROLE_NAME,PARENT) VALUE ('ADMIN',0);
	INSERT INTO PG_ROLES(ROLE_NAME,PARENT) VALUE ('Employee',0);
    INSERT INTO PG_ROLES(ROLE_NAME,PARENT) VALUE ('Customer',0);
    
CREATE TABLE PG_MODULES(
	MODULE_ID INT auto_increment primary KEY,
	MODULE_NAME VARCHAR(100) NOT NULL,
	PARENT INT,
    MODULE_STATUS int default 1
);
	INSERT INTO PG_MODULES(MODULE_NAME,PARENT) VALUE ('Quản lý sản phẩm',0),
													('Quản lý danh mục',1),
													('Quản lý hàng hóa',1),
													('Quản lý nhà cung cấp',1),
													('Quản lý đơn hàng',0),
													('Quản lý khuyến mãi',0),
													('Quản lý tài khoản',0),
													('Quản lý phân quyền',0),
													('Phân quyền',8),
													('Quản lý danh mục chức năng',8);
CREATE TABLE PG_USERS(
	RECORD_ID INT auto_increment PRIMARY KEY,
	USER_ID varchar(50) unique NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME varchar (50) NOT NULL,
	ADDRESS VARCHAR(100),
	PHONE_NUMBER VARCHAR(20) NOT NULL,
	CARD_ID VARCHAR(20),
	EMAIL VARCHAR(100),
	SEX tinyint(1) default 0,
	USER_PASSWORD VARCHAR(50) NOT NULL,
	ROLE_ID INT not null,
	CREATE_TIME DATETIME DEFAULT current_timestamp,
	MODIFIED_TIME DATETIME,
	USER_STATUS INT NOT NULL DEFAULT 1,
	FOREIGN KEY (ROLE_ID) REFERENCES PG_ROLES(ROLE_ID)
);

INSERT INTO PG_USERS(USER_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER, USER_PASSWORD,ROLE_ID) 
VALUES ('admin','admin','painandgain','12345677874','admin',1),
		('khachhang', 'khach','hang','032658795','khachhang',3);
-- LOG ACTION
CREATE TABLE PG_LOG(
	LOG_ID INT auto_increment primary KEY,
	EMPLOYEE_ID INT NOT NULL,
	CREATED_TIME DATETIME default current_timestamp,
	DESCRIPTION VARCHAR(300) NOT NULL,
	LOG_VALUE VARCHAR(300) NOT NULL,
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES PG_USERS(RECORD_ID)
);

INSERT INTO PG_LOG(EMPLOYEE_ID, DESCRIPTION, LOG_VALUE) 
VALUES (1,'add new procedure','ao thun dai tay');

CREATE TABLE PG_SUPPLIERS(
	SUPPLIER_ID INT auto_increment primary key,
	COMPANY_NAME VARCHAR(100) NOT NULL,
	CONTACT_NAME VARCHAR(100) NOT NULL,
	ADDRESS VARCHAR(100),
	REGION VARCHAR(100),
	PHONE VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(100),
	SUPPLIER_STATUS INT DEFAULT 1
);

INSERT INTO PG_SUPPLIERS(COMPANY_NAME, CONTACT_NAME, PHONE) 
VALUES ('Công ty Thiên Trường','Trịnh Lan Hương','01254879635');

CREATE TABLE PG_PRODUCTS(
	PRODUCT_ID INT auto_increment primary key,
	PRODUCT_NAME VARCHAR(100) NOT NULL,
	SUPPLIER_ID INT NOT NULL,
	CATEGORY_ID INT NOT NULL,
	QUANTITY INT DEFAULT 0 NOT NULL check(QUANTITY>=0),
	UNIT_PRICE INT default 0 NOT NULL check(UNIT_PRICE>=0),
	UNIT_ORDER INT DEFAULT 0 NOT NULL check(UNIT_ORDER>=0),
	DESCRIPTION VARCHAR(300),
	PRODUCT_STATUS INT DEFAULT 1 NOT NULL,
	CREATE_TIME DATETIME DEFAULT current_timestamp,
	MODIFIED_TIME DATETIME,
	IS_NEW tinyint(1) DEFAULT 1,
	IS_HOT tinyint(1) default 1,
	FOREIGN KEY (SUPPLIER_ID) REFERENCES PG_SUPPLIERS(SUPPLIER_ID),
	FOREIGN KEY (CATEGORY_ID) REFERENCES PG_CATEGORIES(CATEGORY_ID)
);

INSERT INTO PG_PRODUCTS(PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, QUANTITY, UNIT_PRICE, UNIT_ORDER) 
VALUES ('Áo thun dài tay',1,1,20,50000,75000);

-- SP KHUYEN MAI
CREATE TABLE PG_PRODUCT_SALES(
	SALE_ID INT auto_increment primary KEY,
	PRODUCT_ID INT NOT NULL,
	START_DATE DATETIME NOT NULL,
	END_DATE DATETIME NOT NULL check(END_DATE >= START_DATE),
	SALE_VALUE INT NOT NULL,
	IS_PERCENT tinyint(1) DEFAULT 0,
	SALES_STATUS INT DEFAULT 1,
	FOREIGN KEY (PRODUCT_ID) REFERENCES PG_PRODUCTS(PRODUCT_ID)
);

INSERT INTO PG_PRODUCT_SALES(PRODUCT_ID, START_DATE, END_DATE, SALE_VALUE) 
VALUES (1,'2018/06/17','2018/06/30',15000);

CREATE TABLE PG_PRODUCT_PICTURES(
	PICTURE_SET_ID INT auto_increment primary key,
	PATH VARCHAR(300) NOT NULL,
	PICTURE_TYPE VARCHAR(20),
	PICTURE_STATUS INT DEFAULT 1,
	PRODUCT_ID INT NOT NULL,
	ORDER_INDEX INT NOT NULL,
	FOREIGN KEY (PRODUCT_ID) REFERENCES PG_PRODUCTS(PRODUCT_ID)
);

INSERT INTO PG_PRODUCT_PICTURES(PRODUCT_ID, PATH, ORDER_INDEX) 
VALUES (1,'http://media.bizwebmedia.net/sites/127046/data/images/2017/10/5750153ao_thun_dai_tay_off_white_arrows_chuan_authentic.jpg',1);

-- PHAN QUYEN NG DUNG VOI CAC CHUC NANG
CREATE TABLE PG_ROLE_PERMISSION(
	PERMISSION_ID INT auto_increment primary KEY,
	ROLE_ID INT NOT NULL,
	MODULE_ID INT NOT NULL,
	IS_INSERT tinyint(1) DEFAULT 0,
	IS_UPDATE tinyint(1) DEFAULT 0,
	
	IS_READ tinyint(1) DEFAULT 0,
	PER_STATUS INT DEFAULT 1,
	DESCRIPTION VARCHAR(200),
	FOREIGN KEY (ROLE_ID) REFERENCES PG_ROLES(ROLE_ID),
	FOREIGN KEY (MODULE_ID) REFERENCES PG_MODULES(MODULE_ID)
);

INSERT INTO PG_ROLE_PERMISSION(ROLE_ID, MODULE_ID, IS_INSERT,IS_UPDATE,IS_READ) 
VALUES (1,1,1,1,1),(1,2,1,1,1),(1,3,1,1,1),(1,4,1,1,1),(1,5,1,1,1),(1,6,1,1,1),(1,7,1,1,1),(1,8,1,1,1),(1,9,1,1,1),(1,10,1,1,1)
	,(2,2,1,1,1),(2,3,1,1,1),(2,4,1,1,1),(2,5,1,1,1),(2,6,1,1,1);

CREATE TABLE PG_ORDER_STATUS(
	
	ORDER_STATUS_KEY INT NOT NULL primary KEY,
	ORDER_STATUS_NAME VARCHAR(50) NOT NULL
);
INSERT INTO PG_ORDER_STATUS(ORDER_STATUS_KEY,ORDER_STATUS_NAME) VALUES
	(0,'Hủy'),(1,'Đang xử lý tiếp nhận'),(2,'Đang giao hàng'),(3,'Hoàn thành');

-- DAT HANG
CREATE TABLE PG_ORDERS(
	ORDER_ID INT auto_increment primary KEY,
	CUSTOMER_ID INT NOT NULL,
	
	ORDER_DATE DATETIME,
	APPROVED_DATE DATETIME, 
	ORDER_STATUS_KEY INT DEFAULT 1,
	SHIP_NAME VARCHAR(100),
	SHIP_ADDRESS VARCHAR(300),
	SHIP_PHONE VARCHAR(20),
	
	FOREIGN KEY (CUSTOMER_ID) REFERENCES PG_USERS(RECORD_ID),
	FOREIGN KEY (ORDER_STATUS_KEY) REFERENCES PG_ORDER_STATUS(ORDER_STATUS_KEY)
);

INSERT INTO PG_ORDERS(CUSTOMER_ID,ORDER_DATE,APPROVED_DATE,ORDER_STATUS_KEY,SHIP_NAME,SHIP_ADDRESS,SHIP_PHONE) 
VALUES (2,'2018-6-22','2018-6-24',0,'Anh khánh','102 Trường CHinh','01662108386'),
	(2,'2018-6-20','2018-6-24',2,'Anh minh','102 Trường CHinh','0979954345'),
    (2,'2018-6-19','2018-6-24',3,'Anh long','102 Trường CHinh','016623477');

-- CHI TIET DAT HANG
CREATE TABLE PG_ORDER_DETAILS(
	ORDER_DETAIL_ID INT auto_increment primary KEY,
	ORDER_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,
	AMOUNT INT NOT NULL default 1 check(AMOUNT>=1),
	UNIT_PRICE INT NOT NULL default 0 check( UNIT_PRICE>=0),
	UNIT_SALE INT NOT NULL default 0 check( UNIT_SALE>=0),
	FOREIGN KEY (PRODUCT_ID) REFERENCES PG_PRODUCTS(PRODUCT_ID),
	FOREIGN KEY (ORDER_ID) REFERENCES PG_ORDERS(ORDER_ID)
);

INSERT INTO PG_ORDER_DETAILS(ORDER_ID, PRODUCT_ID,AMOUNT,UNIT_PRICE,UNIT_SALE) 
VALUES (2,1,2,75000,15000),(3,1,2,75000,15000);

  DELIMITER $$
CREATE TRIGGER after_insert_order_detail after insert ON pg_order_details
FOR EACH ROW
BEGIN
	update pg_products set pg_products.QUANTITY = pg_products.QUANTITY - New.AMOUNT where pg_products.PRODUCT_ID = NEW.PRODUCT_ID ;
    
 END$$
 DELIMITER ; 
 
   DELIMITER $$
CREATE TRIGGER after_update_order after Update ON pg_orders
FOR EACH ROW
BEGIN
	if((new.ORDER_STATUS_KEY =0)) then
		update pg_products,pg_order_details set pg_products.QUANTITY = pg_products.QUANTITY + pg_order_details.AMOUNT where pg_products.PRODUCT_ID = pg_order_details.PRODUCT_ID and pg_order_details.ORDER_ID = New.ORDER_ID;
    end if;
END$$
 DELIMITER ;
 
INSERT INTO PG_ORDER_DETAILS(ORDER_ID, PRODUCT_ID,AMOUNT,UNIT_PRICE,UNIT_SALE) 
VALUES (1,1,2,75000,15000);
update pg_orders set pg_orders.ORDER_STATUS_KEY=0 where pg_orders.ORDER_ID=1;
select * from pg_products