package model;
// Generated Jun 16, 2018 10:24:04 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PgCategories generated by hbm2java
 */
@Entity
@Table(name = "pg_categories", catalog = "dath")
public class PgCategories implements java.io.Serializable {

	private Integer categoryId;
	private String categoryName;
	private String description;
	private int sortIndex;
	private int categoryStatus;
	private Set<PgRolePermission> pgRolePermissions = new HashSet<PgRolePermission>(0);
	private Set<PgProducts> pgProductses = new HashSet<PgProducts>(0);

	public PgCategories() {
	}

	public PgCategories(String categoryName, int sortIndex, int categoryStatus) {
		this.categoryName = categoryName;
		this.sortIndex = sortIndex;
		this.categoryStatus = categoryStatus;
	}

	public PgCategories(String categoryName, String description, int sortIndex, int categoryStatus,
			Set<PgRolePermission> pgRolePermissions, Set<PgProducts> pgProductses) {
		this.categoryName = categoryName;
		this.description = description;
		this.sortIndex = sortIndex;
		this.categoryStatus = categoryStatus;
		this.pgRolePermissions = pgRolePermissions;
		this.pgProductses = pgProductses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CATEGORY_ID", unique = true, nullable = false)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "CATEGORY_NAME", nullable = false, length = 100)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "DESCRIPTION", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SORT_INDEX", nullable = false)
	public int getSortIndex() {
		return this.sortIndex;
	}

	public void setSortIndex(int sortIndex) {
		this.sortIndex = sortIndex;
	}

	@Column(name = "CATEGORY_STATUS", nullable = false)
	public int getCategoryStatus() {
		return this.categoryStatus;
	}

	public void setCategoryStatus(int categoryStatus) {
		this.categoryStatus = categoryStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pgCategories")
	public Set<PgRolePermission> getPgRolePermissions() {
		return this.pgRolePermissions;
	}

	public void setPgRolePermissions(Set<PgRolePermission> pgRolePermissions) {
		this.pgRolePermissions = pgRolePermissions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pgCategories")
	public Set<PgProducts> getPgProductses() {
		return this.pgProductses;
	}

	public void setPgProductses(Set<PgProducts> pgProductses) {
		this.pgProductses = pgProductses;
	}

}
