package model;
// Generated Jun 20, 2018 4:50:52 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PgLog generated by hbm2java
 */
@Entity
@Table(name = "pg_log", catalog = "dath")
public class PgLog implements java.io.Serializable {

	private Integer logId;
	private PgUsers pgUsers;
	private Date createdTime;
	private String description;
	private String logValue;

	public PgLog() {
	}

	public PgLog(PgUsers pgUsers, String description, String logValue) {
		this.pgUsers = pgUsers;
		this.description = description;
		this.logValue = logValue;
	}

	public PgLog(PgUsers pgUsers, Date createdTime, String description, String logValue) {
		this.pgUsers = pgUsers;
		this.createdTime = createdTime;
		this.description = description;
		this.logValue = logValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "LOG_ID", unique = true, nullable = false)
	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public PgUsers getPgUsers() {
		return this.pgUsers;
	}

	public void setPgUsers(PgUsers pgUsers) {
		this.pgUsers = pgUsers;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "LOG_VALUE", nullable = false, length = 300)
	public String getLogValue() {
		return this.logValue;
	}

	public void setLogValue(String logValue) {
		this.logValue = logValue;
	}

}
