package model;
// Generated Jun 26, 2018 11:27:45 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PgOrderStatus generated by hbm2java
 */
@Entity
@Table(name = "pg_order_status", catalog = "dath")
public class PgOrderStatus implements java.io.Serializable {

	private int orderStatusKey;
	private String orderStatusName;
	private Set<PgOrders> pgOrderses = new HashSet<PgOrders>(0);

	public PgOrderStatus() {
	}

	public PgOrderStatus(int orderStatusKey, String orderStatusName) {
		this.orderStatusKey = orderStatusKey;
		this.orderStatusName = orderStatusName;
	}

	public PgOrderStatus(int orderStatusKey, String orderStatusName, Set<PgOrders> pgOrderses) {
		this.orderStatusKey = orderStatusKey;
		this.orderStatusName = orderStatusName;
		this.pgOrderses = pgOrderses;
	}

	@Id

	@Column(name = "ORDER_STATUS_KEY", unique = true, nullable = false)
	public int getOrderStatusKey() {
		return this.orderStatusKey;
	}

	public void setOrderStatusKey(int orderStatusKey) {
		this.orderStatusKey = orderStatusKey;
	}

	@Column(name = "ORDER_STATUS_NAME", nullable = false, length = 50)
	public String getOrderStatusName() {
		return this.orderStatusName;
	}

	public void setOrderStatusName(String orderStatusName) {
		this.orderStatusName = orderStatusName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pgOrderStatus")
	public Set<PgOrders> getPgOrderses() {
		return this.pgOrderses;
	}

	public void setPgOrderses(Set<PgOrders> pgOrderses) {
		this.pgOrderses = pgOrderses;
	}

}
