package model;
// Generated Jun 19, 2018 10:38:00 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PgOrders generated by hbm2java
 */
@Entity
@Table(name = "pg_orders", catalog = "dath")
public class PgOrders implements java.io.Serializable {

	private Integer orderId;
	private PgUsers pgUsersByCustomerId;
	private PgUsers pgUsersByEmployeeId;
	private Date orderDate;
	private Date approvedDate;
	private Integer orderStatus;
	private String shipName;
	private String shipAddress;
	private String shipPhone;
	

	public PgOrders() {
	}

	public PgOrders(PgUsers pgUsersByCustomerId, PgUsers pgUsersByEmployeeId) {
		this.pgUsersByCustomerId = pgUsersByCustomerId;
		this.pgUsersByEmployeeId = pgUsersByEmployeeId;
	}

	public PgOrders(PgUsers pgUsersByCustomerId, PgUsers pgUsersByEmployeeId, Date orderDate, Date approvedDate,
			Integer orderStatus, String shipName, String shipAddress, String shipPhone
			) {
		this.pgUsersByCustomerId = pgUsersByCustomerId;
		this.pgUsersByEmployeeId = pgUsersByEmployeeId;
		this.orderDate = orderDate;
		this.approvedDate = approvedDate;
		this.orderStatus = orderStatus;
		this.shipName = shipName;
		this.shipAddress = shipAddress;
		this.shipPhone = shipPhone;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ORDER_ID", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ID", nullable = false)
	public PgUsers getPgUsersByCustomerId() {
		return this.pgUsersByCustomerId;
	}

	public void setPgUsersByCustomerId(PgUsers pgUsersByCustomerId) {
		this.pgUsersByCustomerId = pgUsersByCustomerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID", nullable = false)
	public PgUsers getPgUsersByEmployeeId() {
		return this.pgUsersByEmployeeId;
	}

	public void setPgUsersByEmployeeId(PgUsers pgUsersByEmployeeId) {
		this.pgUsersByEmployeeId = pgUsersByEmployeeId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ORDER_DATE", length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "APPROVED_DATE", length = 19)
	public Date getApprovedDate() {
		return this.approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}

	@Column(name = "ORDER_STATUS")
	public Integer getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(Integer orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "SHIP_NAME", length = 100)
	public String getShipName() {
		return this.shipName;
	}

	public void setShipName(String shipName) {
		this.shipName = shipName;
	}

	@Column(name = "SHIP_ADDRESS", length = 300)
	public String getShipAddress() {
		return this.shipAddress;
	}

	public void setShipAddress(String shipAddress) {
		this.shipAddress = shipAddress;
	}

	@Column(name = "SHIP_PHONE", length = 20)
	public String getShipPhone() {
		return this.shipPhone;
	}

	public void setShipPhone(String shipPhone) {
		this.shipPhone = shipPhone;
	}


}
