package model;
// Generated Jun 26, 2018 11:27:45 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PgRoles generated by hbm2java
 */
@Entity
@Table(name = "pg_roles", catalog = "dath")
public class PgRoles implements java.io.Serializable {

	private Integer roleId;
	private String roleName;
	private Integer parent;
	private Set<PgRolePermission> pgRolePermissions = new HashSet<PgRolePermission>(0);
	private Set<PgUsers> pgUserses = new HashSet<PgUsers>(0);

	public PgRoles() {
	}

	public PgRoles(String roleName) {
		this.roleName = roleName;
	}

	public PgRoles(String roleName, Integer parent, Set<PgRolePermission> pgRolePermissions, Set<PgUsers> pgUserses) {
		this.roleName = roleName;
		this.parent = parent;
		this.pgRolePermissions = pgRolePermissions;
		this.pgUserses = pgUserses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ROLE_ID", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "ROLE_NAME", nullable = false, length = 100)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "PARENT")
	public Integer getParent() {
		return this.parent;
	}

	public void setParent(Integer parent) {
		this.parent = parent;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pgRoles")
	public Set<PgRolePermission> getPgRolePermissions() {
		return this.pgRolePermissions;
	}

	public void setPgRolePermissions(Set<PgRolePermission> pgRolePermissions) {
		this.pgRolePermissions = pgRolePermissions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pgRoles")
	public Set<PgUsers> getPgUserses() {
		return this.pgUserses;
	}

	public void setPgUserses(Set<PgUsers> pgUserses) {
		this.pgUserses = pgUserses;
	}

}
